# Generated by Django 2.0.6 on 2018-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('client', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='browser')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
