# Generated by Django 2.0.6 on 2018-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='person',
            name='client',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='browser'),
        ),
    ]
